name: Generate JMeter Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y jmeter

    - name: Verify JMeter installation
      run: jmeter --version

    - name: Run JMeter Test
      run: |
        jmeter -n -t PetStoreDemo.jmx -l results.jtl

    - name: Generate JMeter Dashboard Report
      run: |
        jmeter -g results.jtl -o jmeter_report

    - name: Upload JMeter Report
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-report
        path: jmeter_report
